Traceback (most recent call last):
  File "process_3_stage.py", line 21, in <module>
    time_struct = list(time.localtime(int(timeData[i][j])))
OSError: [Errno 75] Value too large for defined data type
142889854527948026
14283952531428233810
14298516011429159608
1428677303429019518
14299150531430000443
142890713428045278
1428126431428466107
map over
map over
Traceback (most recent call last):
  File "process_3_stage.py", line 18, in <module>
    rawData[i][j] = locList.index(rawData[i][j])      
ValueError: [39.84835, 116.31126] is not in list
map over
0
0
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
map over
map over
1000
114633
2000
248823
3000
364258
4000
488673
5000
620072
6000
745213
7000
861311
8000
995391
9000
1123859
10000
1249544
11000
1377445
12000
1500735
13000
1617318
14000
1740805
15000
1861644
16000
1983753
17000
2109637
18000
2232645
